# templates for deploy

.deploy:
  stage: deploy
  image: docker:latest
  script:
    - ls -al
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker stack deploy --prune --with-registry-auth --resolve-image never --compose-file=$DOCKER_COMPOSE_FILE $DOCKER_SWARM
  dependencies: []

.undeploy:
  stage: undeploy
  image: docker:latest
  script:
    - docker stack rm $DOCKER_SWARM
  dependencies: []

